testing container

diff --git a/.github/workflows/pre-check.yml b/.github/workflows/pre-check.yml
--- a/.github/workflows/pre-check.yml
+++ b/.github/workflows/pre-check.yml
@@ -15,42 +15,16 @@ on:
 env:
   CARGO_TERM_COLOR: always
 jobs:
-  dup-check:
-    runs-on: dup-check
-    steps:
-      - name: Check for duplicate actions
-        uses: fkirc/skip-duplicate-actions@master
-        with:
-          cancel_others: true
-  code-coverage-mlir-rs:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check for duplicate actions
-        uses: fkirc/skip-duplicate-actions@master
-        with:
-          cancel_others: true
-      - name: set git config
-        run: git config --global --add safe.directory /__w/mlir-rs/mlir-rs
-      - uses: actions/checkout@v4
-      - name: Setup runner
-        run: sudo ./utils/setup.sh
-      - name: Setup mlir-rs
-        run: make setup
-      - name: code-coverage-mlir-rs
-        run: make code-coverage
-      - name: Produce the coverage report
-        uses: insightsengineering/coverage-action@v2
-        with:
-          path: ./cobertura.xml
-          threshold: 80
-          fail: false
-          publish: true
-          coverage-summary-title: "mlir-rs: Code Coverage Summary"
-      - name: print-result
-        shell: bash
-        run: echo "Code Coverage Passed"
   test-mlir-rs:
     runs-on: ubuntu-latest
+    container:
+      image: icr.io/action/rust
+      options: --security-opt seccomp=unconfined
+      env:
+        HOME: /root
+      credentials:
+        username: iamapikey
+        password: ${{ secrets.IBM_CLOUD_REGISTRY_KEY }}
     steps:
       - name: Check for duplicate actions
         uses: fkirc/skip-duplicate-actions@master
@@ -60,7 +34,7 @@ jobs:
         run: git config --global --add safe.directory /__w/mlir-rs/mlir-rs
       - uses: actions/checkout@v4
       - name: Setup runner
-        run: sudo ./utils/setup.sh
+        run: sudo apt install -y valgrind
       - name: Setup mlir-rs
         run: make setup
       - name: Lint and format check
@@ -76,3 +50,57 @@ jobs:
       - name: Testing mlir-rs w/ valgrind
         if: success() || failure()
         run: make test-valgrind
+  # code-coverage-mlir-rs:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Check for duplicate actions
+  #       uses: fkirc/skip-duplicate-actions@master
+  #       with:
+  #         cancel_others: true
+  #     - name: set git config
+  #       run: git config --global --add safe.directory /__w/mlir-rs/mlir-rs
+  #     - uses: actions/checkout@v4
+  #     - name: Setup runner
+  #       run: sudo ./utils/setup.sh
+  #     - name: Setup mlir-rs
+  #       run: make setup
+  #     - name: code-coverage-mlir-rs
+  #       run: make code-coverage
+  #     - name: Produce the coverage report
+  #       uses: insightsengineering/coverage-action@v2
+  #       with:
+  #         path: ./cobertura.xml
+  #         threshold: 80
+  #         fail: false
+  #         publish: true
+  #         coverage-summary-title: "mlir-rs: Code Coverage Summary"
+  #     - name: print-result
+  #       shell: bash
+  #       run: echo "Code Coverage Passed"
+  # test-mlir-rs:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Check for duplicate actions
+  #       uses: fkirc/skip-duplicate-actions@master
+  #       with:
+  #         cancel_others: true
+  #     - name: set git config
+  #       run: git config --global --add safe.directory /__w/mlir-rs/mlir-rs
+  #     - uses: actions/checkout@v4
+  #     - name: Setup runner
+  #       run: sudo ./utils/setup.sh
+  #     - name: Setup mlir-rs
+  #       run: make setup
+  #     - name: Lint and format check
+  #       run: make github-checks
+  #     - name: Testing mlir-rs no sanitizer
+  #       run: make test
+  #     - name: Testing mlir-rs w/ rust address sanitizer 
+  #       if: success() || failure()
+  #       run: make test-address
+  #     - name: Testing mlir-rs w/ rust memory sanitizer
+  #       if: success() || failure()
+  #       run: make test-memory
+  #     - name: Testing mlir-rs w/ valgrind
+  #       if: success() || failure()
+  #       run: make test-valgrind
